# Generated by Django 5.2.5 on 2025-09-04 13:15

import cloudinary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techEdgeApp', '0003_blogpost_likes_count_blogcomment_bloglike_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('icon', models.CharField(default='fas fa-graduation-cap', max_length=50, verbose_name='Icône')),
            ],
            options={
                'verbose_name': 'Catégorie de formation',
                'verbose_name_plural': 'Catégories de formation',
            },
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('short_description', models.CharField(max_length=300, verbose_name='Description courte')),
                ('full_description', models.TextField(verbose_name='Description complète')),
                ('duration', models.CharField(help_text='Ex: 3 mois, 40 heures', max_length=50, verbose_name='Durée')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Prix')),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Date de début')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Date de fin')),
                ('max_participants', models.PositiveIntegerField(default=20, verbose_name='Nombre maximum de participants')),
                ('current_participants', models.PositiveIntegerField(default=0, verbose_name='Participants actuels')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='techEdgeApp.trainingcategory', verbose_name='Catégorie')),
            ],
            options={
                'verbose_name': 'Formation',
                'verbose_name_plural': 'Formations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrainingRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_date', models.DateTimeField(auto_now_add=True, verbose_name="Date d'inscription")),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('confirmed', 'Confirmé'), ('cancelled', 'Annulé'), ('completed', 'Terminé')], default='pending', max_length=20, verbose_name='Statut')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='techEdgeApp.training', verbose_name='Formation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Inscription à une formation',
                'verbose_name_plural': 'Inscriptions aux formations',
                'unique_together': {('user', 'training')},
            },
        ),
    ]
