# Generated by Django 5.2.5 on 2025-09-05 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techEdgeApp', '0004_trainingcategory_training_trainingregistration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='training',
            options={},
        ),
        migrations.RemoveField(
            model_name='training',
            name='category',
        ),
        migrations.RemoveField(
            model_name='training',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='training',
            name='current_participants',
        ),
        migrations.RemoveField(
            model_name='training',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='training',
            name='max_participants',
        ),
        migrations.AddField(
            model_name='training',
            name='available_seats',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='training',
            name='duration',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='training',
            name='full_description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='training',
            name='image',
            field=models.ImageField(upload_to='trainings/'),
        ),
        migrations.AlterField(
            model_name='training',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='training',
            name='short_description',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='training',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='training',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
