# Generated by Django 5.1.4 on 2025-08-21 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techEdgeApp', '0004_projectcategory_alter_project_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(blank=True, choices=[('web', 'Développement Web'), ('mobile', 'Application Mobile'), ('system', 'Système de Gestion'), ('training', 'Formation'), ('consulting', 'Consulting')], max_length=20, null=True, verbose_name='Catégorie'),
        ),
        migrations.DeleteModel(
            name='ProjectCategory',
        ),
    ]
