# Generated by Django 5.1.4 on 2025-08-25 14:55

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('techEdgeApp', '0005_alter_project_category_delete_projectcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Image principale'),
        ),
        migrations.AlterField(
            model_name='service',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Photo'),
        ),
    ]
