# Generated by Django 5.2.5 on 2025-09-05 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techEdgeApp', '0005_alter_training_options_remove_training_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
