# Generated by Django 5.2.5 on 2025-09-05 09:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techEdgeApp', '0006_training_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='training',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
