# Generated by Django 5.2.5 on 2025-09-05 10:20

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techEdgeApp', '0007_training_created_at_training_updated_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='training',
            options={'ordering': ['-created_at'], 'verbose_name': 'Formation', 'verbose_name_plural': 'Formations'},
        ),
        migrations.RemoveField(
            model_name='training',
            name='available_seats',
        ),
        migrations.RemoveField(
            model_name='training',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='training',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='techEdgeApp.trainingcategory', verbose_name='Catégorie'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='training',
            name='current_participants',
            field=models.PositiveIntegerField(default=0, verbose_name='Participants actuels'),
        ),
        migrations.AddField(
            model_name='training',
            name='max_participants',
            field=models.PositiveIntegerField(default=20, verbose_name='Nombre maximum de participants'),
        ),
        migrations.AlterField(
            model_name='training',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='training',
            name='duration',
            field=models.CharField(help_text='Ex: 3 mois, 40 heures', max_length=50, verbose_name='Durée'),
        ),
        migrations.AlterField(
            model_name='training',
            name='full_description',
            field=models.TextField(verbose_name='Description complète'),
        ),
        migrations.AlterField(
            model_name='training',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='training',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='training',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Prix'),
        ),
        migrations.AlterField(
            model_name='training',
            name='short_description',
            field=models.CharField(max_length=300, verbose_name='Description courte'),
        ),
        migrations.AlterField(
            model_name='training',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='training',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Titre'),
        ),
    ]
