# Generated by Django 5.2.5 on 2025-09-05 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techEdgeApp', '0008_alter_training_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingregistration',
            name='user_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='trainingregistration',
            name='user_first_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Prénom'),
        ),
        migrations.AddField(
            model_name='trainingregistration',
            name='user_last_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nom'),
        ),
        migrations.AddField(
            model_name='trainingregistration',
            name='user_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Téléphone'),
        ),
    ]
